"""add relations to account

Revision ID: 050556f92d5c
Revises: c81eebdd640f
Create Date: 2025-10-22 21:27:08.250215

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '050556f92d5c'
down_revision: Union[str, Sequence[str], None] = 'c81eebdd640f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'calls', 'accounts', ['account_id'], ['id'])
    op.add_column('emails', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'emails', 'accounts', ['account_id'], ['id'])
    op.add_column('pushes', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pushes', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pushes', type_='foreignkey')
    op.drop_column('pushes', 'account_id')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'account_id')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_column('calls', 'account_id')
    # ### end Alembic commands ###
