"""fix call.ext_status_code

Revision ID: 7c7d606518a1
Revises: 8cf0e6d84b77
Create Date: 2025-10-23 19:24:06.775105

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c7d606518a1'
down_revision: Union[str, Sequence[str], None] = '8cf0e6d84b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'ext_status_code',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='http status code from external service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'ext_status_code',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='http status code from external service')
    # ### end Alembic commands ###
