"""add realm to account

Revision ID: 8cf0e6d84b77
Revises: 050556f92d5c
Create Date: 2025-10-23 15:43:33.216502

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8cf0e6d84b77'
down_revision: Union[str, Sequence[str], None] = '050556f92d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('realm', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'realm')
    # ### end Alembic commands ###
