"""add integration type

Revision ID: d307289e353f
Revises: 7c7d606518a1
Create Date: 2025-10-23 20:14:27.757947

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd307289e353f'
down_revision: Union[str, Sequence[str], None] = '7c7d606518a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'type')
    # ### end Alembic commands ###
